version: '3.8'
services:

  proxy0: # Bridge mode uses host main internet adapter
    restart: always
    image: runtimeracer/go-socks5-reverseproxy
    env_file: .env
    command: someuser@vpn.myserver.com -R \*:1080:127.0.0.1:1080
    environment:
      - AUTOSSH_PORT=0
    networks:
      - proxy0
#  proxy0: # IPVlan mode uses specific adapter - only managed to get that working under linux host
#    restart: always
#    image: runtimeracer/go-socks5-reverseproxy
#    env_file: .env
#    command: someuser@vpn.myserver.com -R \*:1080:127.0.0.1:1080
#    environment:
#      - AUTOSSH_PORT=0
#    networks:
#      proxy0:
#        ipv4_address: 192.168.80.10

networks:
  proxy0: # Bridge mode uses host main internet adapter
    driver: bridge
#  proxy0: # IPVlan mode uses specific adapter - only managed to get that working under linux host
#    driver: ipvlan
#    driver_opts:
#      parent: enx2a1e4a647354
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.168.80.0/24
#          gateway: 192.168.80.1
#          ip_range: 192.168.80.10/32

