version: '3.7'
services:

  proxy0:
    restart: always
    image: runtimeracer/go-socks5-reverseproxy
    env_file: .env
    command: someuser@vpn.myserver.com -R \*:1080:127.0.0.1:1080
    environment:
      - AUTOSSH_PORT=0
    #network_mode: host
    networks:
      - proxy0

networks:
  proxy0:
    driver: bridge
    driver_opts:
      parent: Ethernet
